//
//  Deadline+CoreDataProperties.swift
//  My IP Port
//
//  Created by Henri Petuker on 7/2/22.
//
//  Autogenerated Class by Core Data. Changed attributes to non optional (how bad is this?)
//
//  Since this is an autogenerated file I disabled SwiftLint Errors of type missing_docs
// swiftlint:disable missing_docs

import Foundation
import CoreData


extension Deadline {
    @nonobjc public class func fetchRequest() -> NSFetchRequest<Deadline> {
        return NSFetchRequest<Deadline>(entityName: "Deadline")
    }

    @NSManaged public var calenderWeek: Int16
    @NSManaged public var changeDate: Date?
    @NSManaged public var creationDate: Date?
    @NSManaged public var deadlineDate: Date
    @NSManaged public var esSymbol: String
    @NSManaged public var id: String
    @NSManaged public var occasion: String
    @NSManaged public var occasionText: String
    @NSManaged public var title: String
    @NSManaged public var type: String
}

extension Deadline: Identifiable {
}
// swiftlint:enable missing_docs
