//
//  FileFamily+CoreDataProperties.swift
//  My IP Port
//
//  Created by Henri Petuker on 7/2/22.
//
//  Autogenerated Class by Core Data. Changed attributes to non optional (how bad is this?)
//
//  Since this is an autogenerated file I disabled SwiftLint Errors of type missing_docs
// swiftlint:disable missing_docs

import Foundation
import CoreData


extension FileFamily {
    @nonobjc public class func fetchRequest() -> NSFetchRequest<FileFamily> {
        return NSFetchRequest<FileFamily>(entityName: "FileFamily")
    }
    @NSManaged public var id: String
    @NSManaged public var matterType: String
    @NSManaged public var registrationDate: Date
    @NSManaged public var title: String
    @NSManaged public var associatedFiles: NSSet
    @NSManaged public var countries: NSSet
}

// MARK: Generated accessors for associatedFiles
extension FileFamily {
    @objc(addAssociatedFilesObject:)
    @NSManaged public func addToAssociatedFiles(_ value: File)

    @objc(removeAssociatedFilesObject:)
    @NSManaged public func removeFromAssociatedFiles(_ value: File)

    @objc(addAssociatedFiles:)
    @NSManaged public func addToAssociatedFiles(_ values: NSSet)

    @objc(removeAssociatedFiles:)
    @NSManaged public func removeFromAssociatedFiles(_ values: NSSet)
}

// MARK: Generated accessors for countries
extension FileFamily {
    @objc(addCountriesObject:)
    @NSManaged public func addToCountries(_ value: StringCD)

    @objc(removeCountriesObject:)
    @NSManaged public func removeFromCountries(_ value: StringCD)

    @objc(addCountries:)
    @NSManaged public func addToCountries(_ values: NSSet)

    @objc(removeCountries:)
    @NSManaged public func removeFromCountries(_ values: NSSet)
}

extension FileFamily: Identifiable {
}
// swiftlint:enable missing_docs
