
//  Since this is an autogenerated file I disabled SwiftLint Errors of type missing_docs
// swiftlint:disable missing_docs

import Foundation
import CoreData


extension StringCD {
    @nonobjc public class func fetchRequest() -> NSFetchRequest<StringCD> {
        return NSFetchRequest<StringCD>(entityName: "StringCD")
    }

    @NSManaged public var name: String
    @NSManaged public var family1: FileFamily?
    @NSManaged public var file1: File?
    @NSManaged public var file2: File?
    @NSManaged public var file3: File?
}

extension StringCD: Identifiable {
}
// swiftlint:enable missing_docs
